services:
  postgres:
    image: postgres:16-alpine
    container_name: aml-case-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aml_case_mgmt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aml_case_mgmt"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
